# Generated by Django 3.0.5 on 2024-02-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
